/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.*;
import java.awt.*;
import Personas.Cliente;
import Personas.Cola;
/**
 *
 * @author manri
 */
public class LogIn extends javax.swing.JFrame {
    private static Cliente cliente = new Cliente();
    
    
    /**
     * Creates new form Catalogo
     */
    public LogIn() {
        initComponents();
    }

    public static Cliente getCliente() {
        return cliente;
    }

    public static void setCliente(Cliente cliente) {
        LogIn.cliente = cliente;
    }
    
    //validar si el usuario corresponde a un usuario en la lista de usuarios. 
    public void usuarioACtual(){
        String usuario = nombreUsuarioTexto.getText();
        Cola c = new Cola();
        Cliente clienteActual = c.buscarCliente(usuario);
        if (clienteActual.getPasssword().equals(contrasenaTexto.getText())) {
            setCliente(clienteActual);
            //y se mueve a la pantalla del menu 
        } else {
            JOptionPane.showMessageDialog(null, "No hay usuarios que con ese nombre de usuario o contraseña en el sistema.");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUsuarioTexto = new javax.swing.JTextField();
        contrasenaTexto = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuarioTexto.setBackground(new java.awt.Color(245, 222, 180));
        nombreUsuarioTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nombreUsuarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioTexto.setBorder(null);
        nombreUsuarioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 410, 40));

        contrasenaTexto.setBackground(new java.awt.Color(245, 222, 180));
        contrasenaTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        contrasenaTexto.setForeground(new java.awt.Color(0, 0, 0));
        contrasenaTexto.setBorder(null);
        getContentPane().add(contrasenaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 390, 40));

        botonIngresar.setBackground(new java.awt.Color(245, 222, 180));
        botonIngresar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        botonIngresar.setText("Ingresar");
        botonIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 130, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/InicioSesion.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JTextField contrasenaTexto;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField nombreUsuarioTexto;
    // End of variables declaration//GEN-END:variables
}
