/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Cliente;
import Interfaz.Administrador.PaginaInicio;
import Personas.Cliente;
import com.sun.tools.javac.Main;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
/**
 *
 * @author manri
 */
public class LogIn extends javax.swing.JFrame {
    
    private static String usuarioActual;
    
    private static final String ruta = "SC304_3C2023_G3/src/main/java/BaseDeDatos/Usuarios.txt";
    String rutaArchivo = System.getProperty("user.dir") + "/" + ruta;
    public LogIn() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public static String getUsuarioActual() {
        return usuarioActual;
    }

    public static void setUsuarioActual(String usuarioActual) {
        LogIn.usuarioActual = usuarioActual;
    }

    
    //validar si el usuario corresponde a un usuario en la lista de usuarios. 
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUsuarioTexto = new javax.swing.JTextField();
        contrasenaTexto = new javax.swing.JTextField();
        botonRegistro = new javax.swing.JButton();
        botonIngresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuarioTexto.setBackground(new java.awt.Color(245, 222, 180));
        nombreUsuarioTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nombreUsuarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioTexto.setBorder(null);
        nombreUsuarioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 410, 40));

        contrasenaTexto.setBackground(new java.awt.Color(245, 222, 180));
        contrasenaTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        contrasenaTexto.setForeground(new java.awt.Color(0, 0, 0));
        contrasenaTexto.setBorder(null);
        contrasenaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaTextoActionPerformed(evt);
            }
        });
        getContentPane().add(contrasenaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 390, 40));

        botonRegistro.setBackground(new java.awt.Color(245, 222, 180));
        botonRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistro.setText("Registro");
        botonRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 110, -1));

        botonIngresar.setBackground(new java.awt.Color(245, 222, 180));
        botonIngresar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        botonIngresar.setText("Ingresar");
        botonIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 130, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InicioSesion.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextoActionPerformed
    //  Boton para ir a registro
    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        SignIn x = new SignIn();
            x.setVisible(true);
            x.pack();
            x.setLocationRelativeTo(null); 
            this.dispose();
    }//GEN-LAST:event_botonRegistroActionPerformed

    //Boton para verificar los clientes y administradores
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String usuario = nombreUsuarioTexto.getText();
        String contrasena = contrasenaTexto.getText();
        setUsuarioActual(usuario);
        if(usuario.equals("Admin") && contrasena.equals("123")){
            PaginaInicio x = new PaginaInicio();
            x.setVisible(true);
            x.pack();
            x.setLocationRelativeTo(null); 
        } else if (validarUsuario(usuario, contrasena)){
            MenuInicial x = new MenuInicial();
            x.setVisible(true);
            x.pack();
            x.setLocationRelativeTo(null); 
            this.dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Usuario y/o contrasena incorrectas");
        }
    }//GEN-LAST:event_botonIngresarActionPerformed
    
    //Metodo para validar el usuario
    private boolean validarUsuario(String usuario, String contrasena) {
        try (BufferedReader br = new BufferedReader(new FileReader(rutaArchivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                Cliente cliente = partesCliente(linea);
                if (cliente != null && cliente.getNombreUsuario().equals(usuario) && cliente.getContrasena().equals(contrasena)) {
                    return true; 
                }
            }
        } catch (IOException e) {
            mostrarError("Error al validar el usuario: " + e.getMessage());
        }
        return false; 
    }
    
    private Cliente partesCliente(String linea) {
        String[] partes = linea.split(",");

        if (partes.length == 5) { 
            String nombre = partes[0].trim();
            String apellidos = partes[1].trim();
            String nombreUsuario = partes[2].trim();
            String contrasena = partes[3].trim();
            String confirmarContrasena = partes[4].trim();

            return new Cliente(nombre, apellidos, nombreUsuario, contrasena, confirmarContrasena, true);
        } else {
            mostrarError("Formato de línea inválido en el archivo de usuarios.");
            return null;
        }
    }
    
    //Metodo de errores
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void contrasenaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JTextField contrasenaTexto;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField nombreUsuarioTexto;
    // End of variables declaration//GEN-END:variables
}
