/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Cliente;

import Interfaz.Cliente.Ordenes.MenuComidas;

/**
 *
 * @author manri
 */
public class MenuInicial extends javax.swing.JFrame {
    private Transaccion transaccionInstance;
    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverInicio = new javax.swing.JButton();
        ingresarMenu = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverInicio.setBackground(new java.awt.Color(245, 222, 180));
        volverInicio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        volverInicio.setForeground(new java.awt.Color(0, 0, 0));
        volverInicio.setText("Volver Inicio de Sesion");
        volverInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(volverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 210, 30));

        ingresarMenu.setBackground(new java.awt.Color(245, 222, 180));
        ingresarMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ingresarMenu.setForeground(new java.awt.Color(0, 0, 0));
        ingresarMenu.setText("Ordenar");
        ingresarMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 190, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuPrincipalUsuario.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverInicioActionPerformed

    private void ingresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarMenuActionPerformed
        MenuComidas x = new MenuComidas(transaccionInstance);
            x.setVisible(true);
            x.pack();
            x.setLocationRelativeTo(null); 
            this.dispose();
    }//GEN-LAST:event_ingresarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresarMenu;
    private javax.swing.JButton volverInicio;
    // End of variables declaration//GEN-END:variables
}
