/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Cliente;

/**
 *
 * @author manri
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTexto = new javax.swing.JTextField();
        apellidosTexto = new javax.swing.JTextField();
        nombreUsuarioTexto = new javax.swing.JTextField();
        contrasenaTexto = new javax.swing.JTextField();
        confirmarContrasenaTexto = new javax.swing.JTextField();
        registroBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreTexto.setBackground(new java.awt.Color(245, 222, 180));
        nombreTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nombreTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreTexto.setBorder(null);
        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, 30));

        apellidosTexto.setBackground(new java.awt.Color(245, 222, 180));
        apellidosTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apellidosTexto.setForeground(new java.awt.Color(0, 0, 0));
        apellidosTexto.setBorder(null);
        getContentPane().add(apellidosTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, 30));

        nombreUsuarioTexto.setBackground(new java.awt.Color(245, 222, 180));
        nombreUsuarioTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nombreUsuarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioTexto.setBorder(null);
        getContentPane().add(nombreUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 370, 30));

        contrasenaTexto.setBackground(new java.awt.Color(245, 222, 180));
        contrasenaTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        contrasenaTexto.setForeground(new java.awt.Color(0, 0, 0));
        contrasenaTexto.setBorder(null);
        getContentPane().add(contrasenaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 370, 30));

        confirmarContrasenaTexto.setBackground(new java.awt.Color(245, 222, 180));
        confirmarContrasenaTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        confirmarContrasenaTexto.setForeground(new java.awt.Color(0, 0, 0));
        confirmarContrasenaTexto.setBorder(null);
        getContentPane().add(confirmarContrasenaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 370, 30));

        registroBoton.setBackground(new java.awt.Color(245, 222, 180));
        registroBoton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        registroBoton.setForeground(new java.awt.Color(0, 0, 0));
        registroBoton.setText("Registrarme");
        registroBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(registroBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 240, 40));

        jButton2.setBackground(new java.awt.Color(245, 222, 180));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Volver a Inicio Sesion");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 190, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Registro.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTexto;
    private javax.swing.JTextField confirmarContrasenaTexto;
    private javax.swing.JTextField contrasenaTexto;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField nombreUsuarioTexto;
    private javax.swing.JButton registroBoton;
    // End of variables declaration//GEN-END:variables
}
