/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Administrador.Proovedores;

import Catalogo.Nodos.NodoProvedores;
import Catalogo.Provedores.Provedores;
import javax.swing.JOptionPane;

/**
 *
 * @author manri
 */
public class CatalogoProvedores extends javax.swing.JFrame {
    
    //Provedores Doble Lista Circular
    NodoProvedores inicioProvedores;
    NodoProvedores finProvedores;
    
    /**
     * Creates new form CatalogoProvedores
     */
    public CatalogoProvedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limpiar = new javax.swing.JButton();
        volverPantallaPrincipal = new javax.swing.JButton();
        agregarProveedores = new javax.swing.JButton();
        editarProveedores = new javax.swing.JButton();
        nombrePostreTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProveedores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        limpiar.setBackground(new java.awt.Color(45, 62, 80));
        limpiar.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 160, 40));

        volverPantallaPrincipal.setBackground(new java.awt.Color(45, 62, 80));
        volverPantallaPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        volverPantallaPrincipal.setText("Volver a la pantalla principal");
        volverPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverPantallaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(volverPantallaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 300, 60));

        agregarProveedores.setBackground(new java.awt.Color(45, 62, 80));
        agregarProveedores.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        agregarProveedores.setText("Agregar Proveedores");
        getContentPane().add(agregarProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 200, 40));

        editarProveedores.setBackground(new java.awt.Color(45, 62, 80));
        editarProveedores.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        editarProveedores.setText("Editar Proveedores");
        getContentPane().add(editarProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 210, 40));

        nombrePostreTexto.setBackground(new java.awt.Color(7, 0, 63));
        nombrePostreTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nombrePostreTexto.setForeground(new java.awt.Color(255, 255, 255));
        nombrePostreTexto.setBorder(null);
        getContentPane().add(nombrePostreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 340, 30));

        listaProveedores.setEditable(false);
        listaProveedores.setBackground(new java.awt.Color(248, 242, 232));
        listaProveedores.setColumns(20);
        listaProveedores.setForeground(new java.awt.Color(0, 0, 0));
        listaProveedores.setRows(5);
        jScrollPane1.setViewportView(listaProveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 390, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AgregarYEditarProovedores.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    private void volverPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverPantallaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverPantallaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     */
    
    public boolean esVaciaProvedores(){
        return inicioProvedores==null&& finProvedores == null;
   }
   
    
 
   //Metodos Provedores Doble Lista Circular    

   public void agregarProvedoresAlPrincipio(){
        String nombre = JOptionPane.showInputDialog("Nombre del provedores:");
        Provedores provedor = new Provedores(nombre);
        NodoProvedores np = new NodoProvedores(); 
        np.setProvedores(provedor);
        if (esVaciaProvedores()){            
            np.setSiguiente(np);
            np.setAnterior(np);
            inicioProvedores = np;
            finProvedores =  inicioProvedores;            
        }else{
            np.setAnterior(finProvedores);
            finProvedores.setSiguiente(np);
            inicioProvedores.setAnterior(np);
            np.setSiguiente(inicioProvedores);
            inicioProvedores = np;        
        }  
    }
   
   public void agregarProvedoresAlFinal(int val){
        String nombre = JOptionPane.showInputDialog("Nombre del provedores:");
        Provedores provedor = new Provedores(nombre);
        NodoProvedores np = new NodoProvedores(); 
        np.setProvedores(provedor);     
        if (esVaciaProvedores()){
            np.setSiguiente(np);
            np.setSiguiente(np);
            inicioProvedores = np;
            finProvedores = inicioProvedores;
        }else{
            np.setSiguiente(finProvedores);
            finProvedores.setSiguiente(np);
            inicioProvedores.setAnterior(np);
            np.setSiguiente(inicioProvedores);
            finProvedores = np;    
        }
        val++;
        np.setTamano(val);
    }
       
    public void editarProvedores() {
        NodoProvedores aux = inicioProvedores;
        while (aux != null) {
            String provedorNom = JOptionPane.showInputDialog("Ingrese el nombre del proveedor que desea modificar: ");
            if (aux.getProvedores().getNombre().equals(provedorNom)) {
                String nuevoNom = JOptionPane.showInputDialog("Nuevo nombre del proveedor:");
                aux.getProvedores().setNombre(nuevoNom);
                break;
            } else {
                JOptionPane.showMessageDialog(null, "No se puede modificar el proveedor que desea: no coincide con ninguno existente.");   
            }
            aux = aux.getSiguiente();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoProvedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoProvedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoProvedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoProvedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoProvedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProveedores;
    private javax.swing.JButton editarProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea listaProveedores;
    private javax.swing.JTextField nombrePostreTexto;
    private javax.swing.JButton volverPantallaPrincipal;
    // End of variables declaration//GEN-END:variables
}
