/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Administrador.Postres;

import Catalogo.Nodos.NodoPostre;
import Catalogo.Postres.Postre;
import javax.swing.JOptionPane;

/**
 *
 * @author manri
 */
public class CatalogoPostres extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoPostres
     */
    
    //Postres Doble Lista Enlazada
    NodoPostre inicioPostre;
    NodoPostre finPostre;
    
    public CatalogoPostres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dulceRadioButton = new javax.swing.JRadioButton();
        saladoRadioButton = new javax.swing.JRadioButton();
        nombrePostreTexto = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        agregarPostre = new javax.swing.JButton();
        editarPostre = new javax.swing.JButton();
        volverPantallaPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPostres = new javax.swing.JTextArea();
        ingredientesPostreTexto = new javax.swing.JTextField();
        precioPostre = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dulceRadioButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dulceRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        dulceRadioButton.setText("Dulce");
        dulceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dulceRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dulceRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        saladoRadioButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        saladoRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        saladoRadioButton.setText("Salado");
        getContentPane().add(saladoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        nombrePostreTexto.setBackground(new java.awt.Color(7, 0, 63));
        nombrePostreTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nombrePostreTexto.setForeground(new java.awt.Color(255, 255, 255));
        nombrePostreTexto.setBorder(null);
        getContentPane().add(nombrePostreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 340, 20));

        limpiar.setBackground(new java.awt.Color(45, 62, 80));
        limpiar.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 160, 40));

        agregarPostre.setBackground(new java.awt.Color(45, 62, 80));
        agregarPostre.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        agregarPostre.setText("Agregar Postre");
        getContentPane().add(agregarPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 160, 40));

        editarPostre.setBackground(new java.awt.Color(45, 62, 80));
        editarPostre.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        editarPostre.setText("Editar Postre");
        getContentPane().add(editarPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 150, 40));

        volverPantallaPrincipal.setBackground(new java.awt.Color(45, 62, 80));
        volverPantallaPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        volverPantallaPrincipal.setText("Volver a la pantalla principal");
        volverPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverPantallaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(volverPantallaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 300, 60));

        listaPostres.setEditable(false);
        listaPostres.setBackground(new java.awt.Color(248, 242, 232));
        listaPostres.setColumns(20);
        listaPostres.setForeground(new java.awt.Color(0, 0, 0));
        listaPostres.setRows(5);
        jScrollPane1.setViewportView(listaPostres);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 400, 370));

        ingredientesPostreTexto.setBackground(new java.awt.Color(7, 0, 63));
        ingredientesPostreTexto.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ingredientesPostreTexto.setForeground(new java.awt.Color(255, 255, 255));
        ingredientesPostreTexto.setBorder(null);
        getContentPane().add(ingredientesPostreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 288, 340, 20));

        precioPostre.setBackground(new java.awt.Color(7, 0, 63));
        precioPostre.setBorder(null);
        getContentPane().add(precioPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 120, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AgregarYEditarPostres.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dulceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dulceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dulceRadioButtonActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    private void volverPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverPantallaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverPantallaPrincipalActionPerformed

    /**
     * @return 
     */
    
    public boolean esVaciaPostres(){
        return inicioPostre==null&&finPostre==null;
   }
    
       //Metodos Postres Doble Lista Enlazada
   
   public void agregarPostresAlPricipio(){
    String nombre = JOptionPane.showInputDialog("Nombre del postre:");
    String descripcion = JOptionPane.showInputDialog("Descripcion: ");
    String categoria = JOptionPane.showInputDialog("Categoría del postre:");
    Postre postre = new Postre(nombre,descripcion,categoria);
    NodoPostre np = new NodoPostre(); 
    np.setPostre(postre);
        if (finPostre == null) { 
            finPostre = np; 
            inicioPostre = np; 
        }else { 
            np.setSiguiente(finPostre); 
            finPostre.setAnterior(np); 
            finPostre = np;
        }
    
   } 
   public void agregarPostresAlFinal(){
    String nombre = JOptionPane.showInputDialog("Nombre del postre:");
    String descripcion = JOptionPane.showInputDialog("Descripcion: ");
    String categoria = JOptionPane.showInputDialog("Categoría del postre:");
    Postre postre = new Postre(nombre,descripcion,categoria);
    NodoPostre np = new NodoPostre(); 
    np.setPostre(postre); 
        if (inicioPostre == null) { 
            finPostre = np; 
            inicioPostre = np; 
        }else{
            np.setSiguiente(np);
            np.setAnterior(inicioPostre);
            inicioPostre = np;
        }
   }  
    
   public void editarPostres() {
        NodoPostre aux = inicioPostre;
        while (aux != null) {
            String postreNom = JOptionPane.showInputDialog("Ingrese el nombre del postre que desea modificar: ");
            if (aux.getPostre().getNombre().equals(postreNom)) {
                String nuevoNom = JOptionPane.showInputDialog("Nuevo nombre del postre:");
                aux.getPostre().setNombre(nuevoNom);
                String nuevaDescr = JOptionPane.showInputDialog("Nueva descripcion: ");
                aux.getPostre().setDescripcion(nuevaDescr);
                String nuevaCateg = JOptionPane.showInputDialog("Nueva categoría del postre:");
                aux.getPostre().setCategoria(nuevaCateg);
                break;
            } else {
                JOptionPane.showMessageDialog(null, "No se puede modificar el postre que desea: no coincide con ninguno existente.");   
            }
            aux = aux.getSiguiente();
        }
    }     
   
    public Postre buscarPostre(String nomPostre){
        NodoPostre aux = inicioPostre;
        Postre postre = null;
        while(aux != null){
            if (aux.getPostre().getNombre().equals(nomPostre)) {
                postre = aux.getPostre();
                break;
            }
             aux = aux.getSiguiente();
        }
        return postre;
    }
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoPostres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPostre;
    private javax.swing.JRadioButton dulceRadioButton;
    private javax.swing.JButton editarPostre;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField ingredientesPostreTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea listaPostres;
    private javax.swing.JTextField nombrePostreTexto;
    private javax.swing.JTextField precioPostre;
    private javax.swing.JRadioButton saladoRadioButton;
    private javax.swing.JButton volverPantallaPrincipal;
    // End of variables declaration//GEN-END:variables
}
